# Generated by Django 6.0.1 on 2026-02-10 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lient_name', models.CharField(max_length=100)),
                ('client_cpf_cnpj', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('system_description', models.TextField()),
                ('system_creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_creation_date', models.DateTimeField(auto_now_add=True)),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('access_log', models.TextField()),
                ('access_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.client')),
                ('access_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.system')),
            ],
        ),
    ]
