# Generated by Django 6.0.1 on 2026-02-10 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_cpf_cnpj', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id_system', models.AutoField(primary_key=True, serialize=False)),
                ('name_system', models.CharField(max_length=100)),
                ('description_system', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_creation_date', models.DateTimeField(auto_now_add=True)),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('access_log', models.TextField()),
                ('access_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.client')),
                ('access_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.system')),
            ],
        ),
    ]
