# Generated by Django 6.0.1 on 2026-02-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='lient_name',
            new_name='client_name',
        ),
    ]
