# Generated by Django 6.0.1 on 2026-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_rename_lient_name_client_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='access_log',
        ),
        migrations.AddField(
            model_name='access',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
