# Generated by Django 6.0.1 on 2026-02-09 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acesso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='nome_cliente',
        ),
        migrations.RenameField(
            model_name='sistema',
            old_name='nome',
            new_name='nome_sistema',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='acesso',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj_cliente',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(default='default@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sistema',
            name='descricao_sistema',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sistema',
            name='id_sistema',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id_acesso', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao_acesso', models.DateTimeField(auto_now_add=True)),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('log_acesso', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_acesso.cliente')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_acesso.sistema')),
            ],
        ),
    ]
