# Generated by Django 6.0.1 on 2026-02-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accesses',
            new_name='Access',
        ),
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': (['-granted_at'],)},
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='access',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('client', 'system'), name='unique_active_access_per_client_system'),
        ),
    ]
