# Generated by Django 6.0.1 on 2026-02-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0002_rename_accesses_access_alter_access_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ['-granted_at']},
        ),
    ]
