# Generated by Django 6.0.1 on 2026-02-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0003_alter_access_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ['-granted_at'], 'verbose_name': 'Acesso', 'verbose_name_plural': 'Acessos'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'Acesso', 'verbose_name_plural': 'Acessos'},
        ),
    ]
