# Generated by Django 6.0.1 on 2026-02-21 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0004_alter_access_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'Sistema', 'verbose_name_plural': 'Sistemas'},
        ),
    ]
